(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

(* Why3 assumption *)
Inductive person :=
  | English : person
  | Swedish : person
  | Danish : person
  | Norwegian : person
  | German : person.
Axiom person_WhyType : WhyType person.
Existing Instance person_WhyType.

(* Why3 assumption *)
Inductive house :=
  | H1 : house
  | H2 : house
  | H3 : house
  | H4 : house
  | H5 : house.
Axiom house_WhyType : WhyType house.
Existing Instance house_WhyType.

(* Why3 assumption *)
Inductive color :=
  | Red : color
  | Green : color
  | White : color
  | Yellow : color
  | Blue : color.
Axiom color_WhyType : WhyType color.
Existing Instance color_WhyType.

(* Why3 assumption *)
Inductive pet :=
  | Dog : pet
  | Bird : pet
  | Cat : pet
  | Horse : pet
  | Fish : pet.
Axiom pet_WhyType : WhyType pet.
Existing Instance pet_WhyType.

(* Why3 assumption *)
Inductive drink :=
  | Tea : drink
  | Coffee : drink
  | Milk : drink
  | Beer : drink
  | Water : drink.
Axiom drink_WhyType : WhyType drink.
Existing Instance drink_WhyType.

(* Why3 assumption *)
Inductive cigars_brand :=
  | Pall_mall : cigars_brand
  | Dunhill : cigars_brand
  | Blends : cigars_brand
  | Blue_masters : cigars_brand
  | Prince : cigars_brand.
Axiom cigars_brand_WhyType : WhyType cigars_brand.
Existing Instance cigars_brand_WhyType.

Parameter of_: house -> color.

Parameter to_: color -> house.

Parameter x: house.

(* Why3 goal *)
Theorem To_of : ((to_ (of_ x)) = x).
Proof.


Qed.

